### PR TITLE
gaOptions, set method

### PR DESCRIPTION
**Pull request by mrsln**

### CODE REVIEW

**Comment by dmitry** [comment]
Looks good. :+1: Changes should be documented in the readme file.

**Comment by mrsln** [comment]
is this acceptable? thanks.

**Comment by dmitry** [comment]
@adamlofting can it be merged now?

**Comment by iyoukeyyewei** [comment]
hope this can be merged soon.

**Comment by chrhsmt** [comment]
:+1:

**Comment by yangshun** [comment]
Can this be merged soon? :smile:

**Comment by pukapukan** [comment]
also waiting for this to get merged :+1:

**Comment by pukapukan** [comment]
@adamlofting any plan on merging this?

**Comment by impronunciable** [comment]
@mrsln Looks good. Can you add some tests so I can merge?

Thanks!

**Comment by impronunciable** [comment]
Merged on #45 Thank you!

**Pull request closed without merging**
