### PR TITLE
Upgrade webpack 4 and babel 7

### LINKED ISSUE #195: Use babel-env instead of preset es2015

### PR DESCRIPTION
**Pull request by anajavi**
This PR saves around 2kB on minified bundle.

It upgrades build to use webpack 4 and babel-preset-env.

What would you think if I also add es6 module build as separate PR?

Closes #195

### CODE REVIEW

**Comment by SimeonC** [comment]
Thanks for the PR, I haven't had the opportunity to look into webpack 4 yet. Once I have done some more research I'll look into this PR.

**Comment by anajavi** [comment]
I tested making es6 module build too.
It seems that the exports in code need restructuring. Without restructuring the tree shaking does not work. So maybe that can wait.

**Comment by anajavi** [comment]
@SimeonC can this be merged? After that I can make an another PR with Babel7 if you like.

**Comment by anajavi** [comment]
Upgraded to babel 7 too.

**Comment by davidchuyaya** [comment]
Hi, why has this not been merged?

**Comment by anajavi** [comment]
Webpack switched to terser from uglify-es. I can update the PR to reflect this if it has chance to be merged. @SimeonC should I update this PR or just close it?

**Comment by SimeonC** [comment]
If you have the time put it in here - I’m going to try deal with at least the PRs this weekend. I know I’ve left it alone far too long.

**Comment by anajavi** [comment]
I added ESM build to this in #310.

**Pull request merged**
