### PR TITLE
v2.3.0

### PR DESCRIPTION
**Pull request by SimeonC**
@yangshun Can you double check I haven't forgotten anything for the release? (Also I don't have npmjs access yet)

### CODE REVIEW

**Comment by yangshun** [comment]
@SimeonC I added you to the package, could you check?

**Comment by SimeonC** [comment]
@yangshun Looks like I have access now, thanks. As a last check there isn't anything else I have to do for the release apart from what's in this PR and creating the release on npm and github?

**Comment by yangshun** [comment]
Nope, looks ok!

**Comment by SimeonC** [comment]
Cool, thanks. I'll try publish to npm now.

**Comment by SimeonC** [comment]
All worked, brand new version published. Thanks for your help!!

**Pull request merged**
