### PR TITLE
Support for cookie flags

### PR DESCRIPTION
**Pull request by hcz1**
Add support for cookieFlags option in GaOptions, this is mainly for applications which are embeddable. It can be set like this 
```
 initialize(gaID, {
    debug,
    gaOptions: { cookieFlags: 'max-age=7200;secure;samesite=none' },
  })
```

### CODE REVIEW

**Comment by jimishshah** [comment]
Can someone merge this for next release please ? I am getting these warning messages on my site
image

**Comment by jimishshah** [comment]
Thanks for the merge, when would the next release please ?

**Comment by GizmoMKD** [comment]
i'm trying with 3.2.0 version and not able to set cookie attributes... 

**_ga** cookie still not secure and **SameSite** not set...

here is options i pass to initialize of ReactGA
```
const gaOptions = {
    gaOptions: { cookieFlags: 'SameSite=None; Secure' },
};
```

**Comment by GizmoMKD** [comment]
> > i'm trying with 3.2.0 version and not able to set cookie attributes...
> > **_ga** cookie still not secure and **SameSite** not set...
> > here is options i pass to initialize of ReactGA
> > ```
> > const gaOptions = {
> >     gaOptions: { cookieFlags: 'SameSite=None; Secure' },
> > };
> > ```
> 
> Try setting like so:
> 
> ```
> gaOptions: { cookieFlags: 'secure;samesite=none' },
> ```

no idea why but this works...

**Comment by hcz1** [comment]
> > > i'm trying with 3.2.0 version and not able to set cookie attributes...
> > > **_ga** cookie still not secure and **SameSite** not set...
> > > here is options i pass to initialize of ReactGA
> > > ```
> > > const gaOptions = {
> > >     gaOptions: { cookieFlags: 'SameSite=None; Secure' },
> > > };
> > > ```
> > 
> > 
> > Try setting like so:
> > ```
> > gaOptions: { cookieFlags: 'secure;samesite=none' },
> > ```
> 
> no idea why but this works...

This is built on analytics.js, which cookieFlags the value of this setting is a semi-colon separated list of lowercase cookie directives and their respective values.

**Pull request merged**
