### PR TITLE
feature: for react 15.0.0 and ...

### PR DESCRIPTION
**Pull request by wasabia**
react 15.0 had change all require('Object.assign') to require('object-assign')

### CODE REVIEW

**Comment by foffer** [comment]
Awesome, was just about to submit a pr for this

**Comment by sheki** [comment]
It would be great to get this merged.

**Comment by sheki** [comment]
It would be great to get this merged asap.

more context https://github.com/reactjs/core-notes/issues/6

**Comment by antoinejaussoin** [comment]
Indeed, would be great to merge this ASAP

**Comment by thangngoc89** [comment]
I would be great to get this merge and a new release at well.

**Comment by ScottDowne** [comment]
@adamlofting are you able to merge this? It looks good to me.

**Comment by sushilk1991** [comment]
Can some one please merge this asap.

**Comment by zebapy** [comment]
Please merge

**Pull request merged**
