### PR TITLE
Added hooks method `useReactGA`

### PR DESCRIPTION
**Pull request by rawnly**
Implemented hook

```js
export const useReactGA = (configsOrTrackingId, options) => {
  const [isInitialized, setInitialized] = useState(false);

  if (!isInitialized) {
    setInitialized(initialize(configsOrTrackingId, options));
  }

  return ReactGA;
};
```

Usage:
```js
useEffect(() => {
    const { pageView } = useReactGA('<YOUR TRACK ID>')
    pageView('/some-path')
}, [])
```

### CODE REVIEW

**Comment by mattgd** [comment]
Hey there! Any word on this PR? Looks like it's failing to install `react@^15.6.1` and `prop-types@^15.5.10` on Travis, but may otherwise be okay.

**Comment by Rawnly** [comment]
I'm trying to update some dependencies, maybe this will pass Travis build

**Comment by alexanderjeurissen** [comment]
For those following this PR, I ran into the same situation and created a small nifty NPM package that creates a ReactGA provider / hook:

https://www.npmjs.com/package/@alexanderjeurissen/use-reactga

I became only later aware of this issue, for now people can use the npm package above if they need this functionality.

**Comment by ffakira** [comment]
Bumped, I am just wondering if the package every going to expand to include some custom hooks. Instead of devs creating their own hooks.

**Pull request closed without merging**
