### PR TITLE
Optionally disable message capitalization

### PR DESCRIPTION
**Pull request by vtambourine**
Can you please explain, why this package force all event parameters to be capitalised?

This pull request show how I added option to disable text capitalisation for my project purpose. Probably, it is worth to have one in the upstream.

### CODE REVIEW

**Comment by yangshun** [comment]
@vtambourine This is great! Would you mind adding some tests for the capitalization option? The PR can be merged after the tests are added.

**Comment by vtambourine** [comment]
Yes, sure!

**Comment by yangshun** [comment]
Ping @vtambourine . We would very much like to get this PR merged in. Could you resolve conflicts and fix linter errors if any?

**Comment by BrandonMathis** [comment]
thankyou for doing this @vtambourine !

**Comment by yangshun** [comment]
Closed in favour of #63

**Pull request closed without merging**
