### PR TITLE
v2.3.1

### PR DESCRIPTION
**Pull request by SimeonC**
Fix that pesky package param.

### CODE REVIEW

**Comment by karanjthakkar** [comment]
@SimeonC I think there's still some issue with the final dist. When I do this:

```
import ga from 'react-ga';
ga.initialize('UA-xx');
```

I get `undefined is not a function`. The ga object doesn't contain any keys 🤔

**Comment by karanjthakkar** [comment]
Oops. Just saw: https://github.com/react-ga/react-ga/issues/165#issuecomment-331814952 I'll switch to 2.2.0 for now 👍

**Comment by SimeonC** [comment]
Closing, will release a 2.3.2 that _actually works_ as stated in #165 ASAP, sorry again for the problems and confusion.
(Also that travis build has been pending for several hours now...)

**Comment by karanjthakkar** [comment]
No worries. Appreciate the work you're putting into fixing this 💯

**Pull request closed without merging**
