### PR TITLE
Custom Dimensions and Metrics

### PR DESCRIPTION
**Pull request by comamitc**
The purpose of this PR is to add functionality to send custom dimensions and trackers to Universal Analytics. (https://github.com/mozilla/react-ga/issues/25)

### CODE REVIEW

**Comment by adamlofting** [comment]
@comamitc thanks so much for writing this.

Please excuse my extremely slow reply. :dizzy_face: My notifications were setup wrong and I've just seen a bunch of issues and PRs people have filed against this repo today.

I have a few minutes free now to start reviewing this.

**Comment by adamlofting** [comment]
@comamitc this is looks great. 

I'd like to add some tests to this in `test/index.test.js`

Is that something you'd like to work on? Don't worry if not as I can pick it up otherwise.

**Comment by metacortex** [comment]
+1

**Comment by impronunciable** [comment]
This is cool. I can merge this after adding some tests and solving conflicts.

**Comment by yangshun** [comment]
With https://github.com/react-ga/react-ga/pull/45, users can do: 

```
ga.set({
  dimension1: '10001',
  metric1: '10002',
});
```

and it serves the purpose of this PR. Please use `ga.set` instead 😄.

**Pull request closed without merging**
