### PR TITLE
Fix outbound link target blank

### PR DESCRIPTION
**Pull request by skattyadz**
See #71

Let me know if you'd like any changes. Also I don't know what level of testing you expect on this

I've also added checks for meta keys and the middle button which will all open in new tabs/windows

`OutboundLink.trackLink` requires a function as the second parameter so I've added a no-op function there

### CODE REVIEW

**Comment by skattyadz** [comment]
Just noticed that second commit broke 2 tests. I'll fix those tests but the code itself should be good to review

**Comment by efernandesng** [comment]
Hi

This PR will be merged? Would be nice :)

**Comment by alexdavid** [comment]
@yangshun any update on this? This is blocking our team

**Comment by SimeonC** [comment]
Hi guys, just got collaborator status. This is next on my list to look into, so I'll get the tests working correctly then get this merged. I know it's been nearly a year so if I can I'll just merge then fix if there aren't any other issues.

**Comment by skattyadz** [comment]
👍👍👍 Good stuff

**Pull request merged**
