### PR TITLE
Created typings

### PR DESCRIPTION
**Pull request by lennardschutter**
Included typings for the project.

### CODE REVIEW

**Comment by marcomorain** [comment]
👍

**Comment by jrsquared** [comment]
Any chance we can get this merged? Is this project still active?

**Comment by polco** [comment]
there are typings available on npm already: ```npm i @types/react-ga```

**Comment by jrsquared** [comment]
Perfect. This PR should be closed with that info...

**Comment by yangshun** [comment]
As mentioned by @polco , please refer to the typing available at DefinitelyTyped

**Pull request closed without merging**
